### ISSUE TITLE
Tracking issue for complete 32-bit support

### ISSUE THREAD

**Issue by navaati** [prometheus/client_rust#207]
There is a number of small issues making usage of the lib on 32-bit systems (such as embedded chips) impossible or limited. I’ll collate them in this issue with the relevant PRs when I or someone else tackle them, in order to avoid opening many issues but still remember the list.

- [ ] Some 32 bit platforms are not supported #201 #203
- [ ] u32 is not supported for Counter #206 
- [ ] f32 is not supported for Counter
- [ ] f32 is not supported for Gauge
- [ ] i32 is not supported for Gauge
- [ ] Histograms force use of f64: this one is not a _blocker_ as Histograms use a RWLock rather than Atomics so it works (f64 support is always present via emulation), but it may be slower or consume more memory than wished for

**Comment by navaati** [comment]
@mxinden One thing I’m not sure about is Examplars: I know @brocaar added support for the _encoding_ of them in #173 but I don’t know if they are tested or if they require Atomics, as I don’t really know how to use them. So their support status on 32-bit machines is unknown to me.
